import json
import operator
from typing import Annotated, Any

import requests
from config import get_github_token, init_settings  # type: ignore[import-untyped]
from dotenv import load_dotenv
from fastapi import FastAPI
from github import Auth, Github, GithubException
from langchain.agents import create_agent
from langchain.messages import AIMessage, AnyMessage
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel
from typing_extensions import TypedDict

load_dotenv()

# Initialize settings at startup
init_settings()

app = FastAPI()


class WebhookPayload(BaseModel):
    action: str
    repository: dict[str, Any]
    pull_request: dict[str, Any]


class MessageState(TypedDict):
    messages: Annotated[list[AnyMessage], operator.add]
    diffs: list[dict[str, str]] | None
    files: list[dict[str, str]] | None
    output: Any | None
    repo_full: str | None
    pr_number: int | None
    static_analysis_report: list[dict[str, str | int]] | None


def fetch_pr_files(state: MessageState) -> dict[str, list[dict[str, str]]]:
    """Fetch the pull request based on repo fullname and PR number, and return the list of diffs object."""
    auth = Auth.Token(get_github_token())
    gh = Github(auth=auth)

    repo_full = state["repo_full"]
    pr_number = state["pr_number"]

    if repo_full is None:
        raise ValueError("repo_full is required")
    if pr_number is None:
        raise ValueError("pr_number is required")

    repo = gh.get_repo(repo_full)
    pr = repo.get_pull(pr_number)

    diffs: list[dict[str, str]] = []
    files: list[dict[str, str]] = []

    for f in pr.get_files():
        diffs.append(
            {
                "filename": f.filename,
                "patch": f.patch if f.patch else "",
            }
        )

        if f.filename.endswith(".py"):
            try:
                file_content = repo.get_contents(f.filename, ref=pr.head.sha)
                if isinstance(file_content, list):
                    continue
                content: str = file_content.decoded_content.decode("utf-8")
                files.append({"filename": f.filename, "content": content})
            except GithubException as e:
                print(f"Error fetching file {f.filename}: {e.status} - {e.data}")
                continue
            except (OSError, AttributeError) as e:
                print(f"Error decoding file {f.filename}: {e}")
                continue

    return {"diffs": diffs, "files": files}


def llm_review_node(state: MessageState) -> dict[str, Any]:
    """LLM will review the PR diff and suggest code improvements."""
    static_report = state.get("static_analysis_report", [])
    static_report_text = ""
    if static_report:
        static_report_text = (
            "\n    Additionally, consider the following static analysis "
            "report generated by ruff:\n"
            f"    {json.dumps(static_report, indent=2)}\n\n"
            "    Integrate these findings into your review and provide a "
            "comprehensive analysis combining both dynamic code review and "
            "static analysis results."
        )

    system_prompt = (
        "You are a helpful coding assistant tasked with reviewing pull "
        "request diffs and suggesting code improvements, best practices, and "
        "coding standards feedback.\n\n"
        "Return your response as valid JSON with this exact format:\n"
        "{\n"
        '    "summary": "brief summary of the review",\n'
        '    "issues": [\n'
        "        {\n"
        '            "file": "filename.py",\n'
        '            "line": 45,\n'
        '            "type": "security|bug|style|improvement",\n'
        '            "severity": "high|medium|low",\n'
        '            "message": "description of the issue",\n'
        '            "suggestion": "suggested fix or improvement"\n'
        "        }\n"
        "    ],\n"
        '    "suggested_patch": "optional suggested code changes"\n'
        "}\n\n"
        "Review the provided diff and identify:\n"
        "1. Bugs or logical errors\n"
        "2. Violations of coding standards\n"
        "3. Security issues - Hardcoded secrets, SQL injection, unsafe "
        "deserialization, unvalidated inputs\n"
        "4. Suggestions for improvement - Missing error handling, better "
        f"variable naming, better architecture{static_report_text}"
    )

    agent: Any = create_agent(
        model="gpt-4o-mini",
        system_prompt=system_prompt,
    )

    result = agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": f"""
                        Review this PR diff and point out
                        1. Bugs
                        2. Violations of coding standards
                        3. Security issues
                        4. Suggestions for improvement

                        Diff:
                        {state["diffs"]}
                    """,
                },
            ],
        },
    )

    return {"messages": result["messages"], "output": result["messages"][-1]}


def post_review_comment(state: MessageState) -> dict[str, list[AIMessage]]:
    """Post review comments into the github repo."""
    final_output = state["messages"][-1].content
    convert_to_obj = (
        json.loads(final_output)
        if final_output and isinstance(final_output, str)
        else None
    )
    auth = Auth.Token(get_github_token())
    gh = Github(auth=auth)

    repo_full = state["repo_full"]
    pr_number = state["pr_number"]

    if repo_full is None:
        raise ValueError("repo_full is required")
    if pr_number is None:
        raise ValueError("pr_number is required")

    repo = gh.get_repo(repo_full)
    pr = repo.get_pull(pr_number)

    comment_body = "### 🤖 AI Code Review\n"

    if convert_to_obj and "issues" in convert_to_obj:
        for issue in convert_to_obj["issues"]:
            comment_body += f"""
            **File:** {issue["file"]}
            **Issue:** {issue["message"]}
            **Suggestion:** {issue["suggestion"]}
            ---
        """
    pr.create_issue_comment(comment_body)

    return {"messages": [AIMessage("Done.")]}


def static_analysis(state: MessageState) -> dict[str, list[dict[str, Any]]]:
    """Static analysis only the changed files."""
    url = "http://localhost:8080/analyze"
    http_ok = 200
    issues: list[dict[str, Any]] = []
    try:
        response = requests.post(url=url, json={"files": state["files"]}, timeout=30)

        if response.status_code == http_ok:
            data = response.json()
            print("Aravind Data: ", data)
            issues = data["issues"]
    except (requests.RequestException, KeyError, ValueError) as e:
        print(f"Error in static analysis: {e!s}")

    return {"static_analysis_report": issues}


@app.get("/")
def hello_world():
    return {"hello": "world"}


@app.post("/webhook/pr")
async def handle_pr(pr: WebhookPayload):
    if pr.action not in ["opened", "synchronize", "reopened"]:
        return {"status": "ignored"}

    repo_full = pr.repository["full_name"]
    pr_number = pr.pull_request["number"]

    agent_builder = StateGraph(MessageState)

    agent_builder.add_node("fetch_pr_files", fetch_pr_files)
    agent_builder.add_node("llm_review_node", llm_review_node)
    agent_builder.add_node("static_analysis", static_analysis)
    agent_builder.add_node("post_review_comment", post_review_comment)

    agent_builder.add_edge(START, "fetch_pr_files")
    agent_builder.add_edge("fetch_pr_files", "static_analysis")
    agent_builder.add_edge("static_analysis", "llm_review_node")
    agent_builder.add_edge("llm_review_node", "post_review_comment")
    agent_builder.add_edge("post_review_comment", END)

    graph = agent_builder.compile()

    initial_state: MessageState = {
        "messages": [],
        "diffs": None,
        "output": None,
        "repo_full": repo_full,
        "pr_number": pr_number,
        "static_analysis_report": None,
        "files": None,
    }
    result = graph.invoke(initial_state)  # type: ignore[arg-type]

    final_output = (
        result["messages"][-1].content if result["messages"] else "No review generated"
    )

    return {
        "status": "processing",
        "data": {"repo_full": repo_full, "pr_number": pr_number},
        "output": final_output,
    }
